repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
          - id: check-yaml
          - id: check-json
          - id: check-toml
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: detect-private-key
          - id: check-ast
    - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: v0.11.4
      hooks:
          # Run the linter.
          - id: ruff
            args: [--fix]
          # Run the formatter.
          - id: ruff-format
